# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  PREPARE_DATA: prepare
  TRAIN_DATA: train.tsv
  TEST_DATA: test.tsv


source_data_url: https://drive.google.com/file/d/13A0RtvZZanHXKZNbz5JKwjjO2FedNQCR/view


source_download_dirs:
   data_dir: data
   data_file: data.xml
